"""Add column customer_fullname

Revision ID: b2a76cd38fbd
Revises: a0c5f429b18a
Create Date: 2022-03-29 10:41:53.867049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2a76cd38fbd"
down_revision = "a0c5f429b18a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("customer_fullname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "customer_fullname")
    # ### end Alembic commands ###
